/*

		DDL - LINGUAGEM DE DEFINIÇÃO DE DADOS

*/

CREATE DATABASE PCLINICAmanha;

USE PCLINICAmanha;

CREATE TABLE Clinica(
	IdClinica INT PRIMARY KEY IDENTITY,
	RazaoSocial VARCHAR(200) NOT NULL,
	Endereco VARCHAR(200)
);

CREATE TABLE Dono(
	IdDono INT PRIMARY KEY IDENTITY,
	NomeDono VARCHAR(200) NOT NULL
);

CREATE TABLE TipoPet(
	IdTipoPet INT PRIMARY KEY IDENTITY,
	Titulo VARCHAR(200)
);

CREATE TABLE Veterinario(
	IdVet INT PRIMARY KEY IDENTITY,
	NomeVeterinario VARCHAR(200) NOT NULL,
	CRMV VARCHAR(6) NOT NULL,
	IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica)
);

CREATE TABLE Pet(
	IdPet INT PRIMARY KEY IDENTITY,
	NomePet VARCHAR(200) NOT NULL,
	Telefone CHAR(11),
	IdDono INT FOREIGN KEY REFERENCES Dono(IdDono),
	IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica)
);

CREATE TABLE Raca(
	IdRaca INT PRIMARY KEY IDENTITY,
	Titulo VARCHAR(200) NOT NULL,
	IdTipoPet INT FOREIGN KEY REFERENCES TipoPet(IdTipoPet)

);

CREATE TABLE Atendimento(
	IdAtendimento INT PRIMARY KEY IDENTITY,
	Data DATE,
	Descricao VARCHAR(200),
	IdVet INT FOREIGN KEY REFERENCES Veterinario(IdVet),
	IdPet INT FOREIGN KEY REFERENCES Pet(IdPet) 
);