/*
					DDL
*/

CREATE DATABASE LOCADORAAmanha;

USE LOCADORAAmanha;

CREATE TABLE Marca(
	IdMarca INT PRIMARY KEY IDENTITY,
	NomeMarca VARCHAR(200) NOT NULL
);

CREATE TABLE Modelo(
	IdModelo INT PRIMARY KEY IDENTITY,
	NomeModelo VARCHAR(200) NOT NULL,
	IdMarca INT FOREIGN KEY REFERENCES Marca(IdMarca)
);

CREATE TABLE Empresa(
	IdEmpresa INT PRIMARY KEY IDENTITY,
	NomeEmpresa VARCHAR(200) NOT NULL,
);

CREATE TABLE Veiculo(
	IdVeiculo INT PRIMARY KEY IDENTITY,
	Placa VARCHAR(100) NOT NULL,
	IdEmpresa INT FOREIGN KEY REFERENCES Empresa (IdEmpresa),
	IdModelo INT FOREIGN KEY REFERENCES Modelo(IdModelo)
);

CREATE TABLE Cliente(
	IdCliente INT PRIMARY KEY IDENTITY,
	NomeCliente VARCHAR(200) NOT NULL,
	CPF CHAR(11)
);

CREATE TABLE Aluguel(
	IdAluguel INT PRIMARY KEY IDENTITY,
	DataInicio DATE,
	DataFim DATE,
	IdCliente INT FOREIGN KEY REFERENCES Cliente(IdCliente),
	IdVeiculo INT FOREIGN KEY REFERENCES Veiculo(IdVeiculo)
);


